services:
    z407-controller:
        volumes:
            - /var/run/dbus:/var/run/dbus
        devices:
            - /dev/serial0
        ports:
            - 8000:8000
        image: ghcr.io/angelolz/z407-controller
        restart: unless-stopped
