version: "3.8"
services:
  z407:
    image: ghcr.io/angelolz/z407-controller:latest
    container_name: z407-remote-api
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    ports:
      - 8000:8000
    restart: unless-stopped
